<?php
/**
 * @var $block Magento\Catalog\Block\Product\View;
 */
?>
<button id="modal-btn">Open Modal</button>
<form data-mage-init='{"validation": {}}' class="form" id="custom-form" method="post" autocomplete="off">
    <fieldset>
        <div id="modal-content">
            <div class="telephone">
                <div class="title_telephone">Telephone number:</div>
                <input type="text" name="customer_telephone" class="customer_telephone" data-validate="{required:true}" pattern="[+](380) (97|96|68|50|95|66) [0-9]{3}-[0-9]{2}-[0-9]{2}" placeholder="+380 XX XXX-XX-XX">
            </div>
            <div class="name">
                <div class="title_name">Name:</div>
                <input type="text" name="customer_name" class="customer_name">
            </div>
            <div class="email">
                <div class="title_email">Email:</div>
                <input type="text" name="customer_email" class="customer_email" data-validate="{required:true, 'validate-email':true}" >
            </div>
            <div class="address">
                <div class="title_address">Address:</div>
                <input type="text" name="customer_address" class="customer_address">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" id="sub" class="action primary tocart">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>
<script>
    require([
        'jquery',
        'moment',
        'Magento_Ui/js/modal/modal'
    ], function($, moment, modal) {
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            buttons: [{
                text: $.mage.__('Close'),
                class: 'modal-close',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        modal(options, $('#custom-form'));
        $("#modal-btn").on('click',function(){
            $("#custom-form").modal("openModal");
        });

        $("#sub").on('click', function () {
            setTimeout(function() {
                var className = $("input[name='customer_telephone']").attr('class');
                if (className.indexOf('mage-error') === -1) {
                    var date = moment().format("YYYY/MM/DD HH:mm:ss");
                    var product = "<?php echo $block->getProduct()->getName() ?>";
                    var price = "<?php echo $block->getProduct()->getFinalPrice() ?>";
                    var telephone = $("input[name='customer_telephone']").val();
                    var name = $("input[name='customer_name']").val() !== ''
                        ? $("input[name='customer_name']").val() : "not indicated";
                    var email = $("input[name='customer_email']").val();
                    var address = $("input[name='customer_address']").val() !== ''
                        ? $("input[name='customer_address']").val() : "not indicated";
                    var url = "<?php echo $block->getUrl('purchase/index/save') ?>";
                    jQuery.ajax({
                        url: url,
                        type: "POST",
                        data: {
                            purchase_date: date,
                            product: product,
                            purchase_price: price,
                            telephone_customer: telephone,
                            name_customer: name,
                            email_customer: email,
                            address_customer: address
                        },
                        showLoader: true,
                    });
                }
            }, 200);
        });
    });
</script>
